openapi: 3.0.3
info:
  title: Easyappz Payments API
  version: 1.3.0
  description: |
    API endpoints for Telegram Payments integration using a safe invoice sender with HTTP fallback.

    Notes:
    - Prices are constructed in minor currency units (RUB -> kopecks) and validated as positive integers.
    - First attempt uses node-telegram-bot-api with an array of objects for prices (never a string).
    - If Telegram returns "can't parse prices JSON object", server retries through direct HTTP with application/x-www-form-urlencoded and prices as JSON string.
servers:
  - url: http://localhost:3001
paths:
  /api/hello:
    get:
      summary: Hello endpoint
      responses:
        '200':
          description: Successful hello response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from API!
  /api/status:
    get:
      summary: Status endpoint
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-01-01T12:00:00.000Z'
  /api/payments/product:
    get:
      summary: Get product info for the Arabic course
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/payments/prices-preview:
    get:
      summary: Build and validate Telegram prices payload
      description: Returns sanitized prices array to be sent to Telegram, its JSON string, validation status and any errors.
      responses:
        '200':
          description: Prices preview and validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PricesPreviewResponse'
              examples:
                valid:
                  value:
                    currency: RUB
                    prices:
                      - label: "Арабский курс"
                        amount: 550000
                    rawJSON: '[{"label":"Арабский курс","amount":550000}]'
                    valid: true
  /api/payments/invoice:
    post:
      summary: Send invoice to a Telegram chat (safe with fallback)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceRequest'
            examples:
              example1:
                value:
                  chatId: 123456789
      responses:
        '200':
          description: Invoice dispatch result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
              examples:
                success:
                  value:
                    ok: true
                    data:
                      message_id: 100
                      chat:
                        id: 123456789
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
              examples:
                invalidChatId:
                  value:
                    ok: false
                    error: 'chatId is required and must be a number > 0'
        '500':
          description: Server or Telegram API error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
              examples:
                telegramPricesParseError:
                  value:
                    ok: false
                    error: 'ETELEGRAM: 400 Bad Request: can\'t parse prices JSON object'
                    details: '{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse prices JSON object"}'
  /api/payments/telegram/invoice/test:
    post:
      summary: Manually trigger sending an invoice to a chat (diagnostic)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceRequest'
            examples:
              example1:
                value:
                  chatId: 123456789
      responses:
        '200':
          description: Result of sendInvoiceSafe (ok=true) or detailed error (ok=false)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
  /api/payments/telegram/health:
    get:
      summary: Configuration health for Telegram Payments
      description: Returns current currency, masked provider token, minor price value, and JSON preview of prices.
      responses:
        '200':
          description: Health payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  currency:
                    type: string
                    example: RUB
                  providerTokenMasked:
                    type: string
                    example: '381764...0649'
                  priceMinor:
                    type: integer
                    example: 550000
                  pricesPreview:
                    type: string
                    example: '[{"label":"Арабский курс","amount":550000}]'
  /api/payments/telegram/meta:
    get:
      summary: Get Telegram bot metadata (username and deep-links)
      description: Returns bot username and deep-links for opening the bot in mobile/desktop/web Telegram with a start parameter.
      responses:
        '200':
          description: Bot metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  botUsername:
                    type: string
                    example: my_cool_bot
                  deepLinks:
                    type: object
                    properties:
                      mobile:
                        type: string
                        example: tg://resolve?domain=my_cool_bot&start=buy_arabic_course
                      desktop:
                        type: string
                        example: https://t.me/my_cool_bot?start=buy_arabic_course
                      web:
                        type: string
                        example: https://t.me/my_cool_bot?start=buy_arabic_course
        '500':
          description: Bot metadata is not available yet
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bot username is not initialized
                  details:
                    type: string
                    example: Telegram getMe() has not provided a username yet. Try again later.
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: arabic_course_001
        title:
          type: string
          example: Арабский курс
        description:
          type: string
          example: Интенсивный онлайн‑курс арабского языка для начинающих.
        currency:
          type: string
          enum: [RUB]
          example: RUB
        price:
          type: number
          example: 5500
    PriceItem:
      type: object
      required: [label, amount]
      properties:
        label:
          type: string
          description: Display label of the price line (1..32 symbols)
          example: "Арабский курс"
        amount:
          type: integer
          description: Amount in minor currency units (RUB -> kopecks)
          example: 550000
    PricesPreviewResponse:
      type: object
      properties:
        currency:
          type: string
          example: RUB
        prices:
          type: array
          items:
            $ref: '#/components/schemas/PriceItem'
        rawJSON:
          type: string
          description: JSON.stringify(prices) result used for debugging serialization issues
          example: '[{"label":"Арабский курс","amount":550000}]'
        valid:
          type: boolean
          example: true
    InvoiceRequest:
      type: object
      required: [chatId]
      properties:
        chatId:
          type: number
          description: Telegram chat ID to send invoice to
          example: 123456789
    InvoiceResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        data:
          description: Raw Telegram API result when ok=true
          nullable: true
        message:
          type: string
          nullable: true
        error:
          description: Error details when ok=false
          nullable: true
        details:
          description: Optional extended error details (e.g., Telegram response body) for debugging
          nullable: true
